// main.js — boot sequence. Lead-owned; subsystem agents do not edit this file.
//
// Order matters:
//   1. engine + scene
//   2. config (quality preset guessed, refined later by benchmark)
//   3. register every subsystem
//   4. init() them in dependency order
//   5. post-processing
//   6. bind the loop and run

import {
  Engine, Scene, FreeCamera, Vector3, Color4,
} from './core/bjs.js';
import * as BJS from './core/bjs.js';
import { Ctx, EV } from './core/ctx.js';
import { Config, guessPreset, QUALITY } from './core/config.js';
import { Rng } from './core/rng.js';
import { Loop } from './core/loop.js';
import { Post } from './core/post.js';

import Materials from './mat/index.js';
import World from './world/index.js';
import Track from './track/index.js';
import Play from './play/index.js';
import Character from './char/index.js';
import Collision from './coll/index.js';
import Fx from './fx/index.js';
import Audio from './audio/index.js';
import Ui from './ui/index.js';

// Modules are init()'d in this order. Anything that reads another module in
// init() must come after it.
const MODULES = [
  ['mat',   Materials],
  ['world', World],
  ['play',  Play],
  ['track', Track],
  ['char',  Character],
  ['coll',  Collision],
  ['fx',    Fx],
  ['audio', Audio],
  ['ui',    Ui],
];

export async function boot(opts = {}) {
  const canvas = document.getElementById('c');

  const engine = new Engine(canvas, true, {
    preserveDrawingBuffer: true,   // required for screenshot capture
    stencil: false,
    antialias: true,
    powerPreference: 'high-performance',
    failIfMajorPerformanceCaveat: false,
  }, false);
  engine.enableOfflineSupport = false;

  const scene = new Scene(engine);
  scene.clearColor = new Color4(0.96, 0.94, 0.905, 1);
  scene.autoClear = true;
  scene.autoClearDepthAndStencil = true;
  scene.blockMaterialDirtyMechanism = true;
  scene.skipPointerMovePicking = true;

  const ctx = new Ctx();
  ctx.engine = engine;
  ctx.scene = scene;
  ctx.canvas = canvas;

  const presetName = opts.preset || guessPreset();
  const config = new Config(presetName);
  config.showDebug = !!opts.debug;
  config.captureMode = !!opts.capture;
  if (opts.seed !== undefined) config.seed = opts.seed >>> 0;
  ctx.config = config;
  ctx.rng = new Rng(config.seed);

  engine.setHardwareScalingLevel(1 / config.q.scale);

  // --- camera ---
  const cam = new FreeCamera('cam', new Vector3(0, config.tune.camHeight, -config.tune.camDistance), scene);
  cam.minZ = 0.35;
  cam.maxZ = 320;
  cam.fov = config.tune.camFovBase;
  cam.setTarget(new Vector3(0, 1, 6));
  scene.activeCamera = cam;
  // input is handled entirely by play/ — never attach Babylon's own controls

  // --- subsystems ---
  for (const [name, Klass] of MODULES) {
    ctx.register(name, new Klass(ctx));
  }
  for (const [name] of MODULES) {
    const m = ctx.get(name);
    if (typeof m.init === 'function') m.init();
  }
  // Restarting touches several subsystems in a required order, so it is a lead
  // concern rather than something any one subsystem owns. ui/ calls this.
  ctx.restart = () => {
    ctx.time = 0;
    ctx.rng.reset();
    ctx.get('play').reset();
    ctx.get('track').reset();
    ctx.loop.setPaused(false);
    ctx.emit(EV.RUN_START, null);
  };

  ctx.get('play').reset();
  ctx.get('track').reset();
  ctx.emit(EV.RUN_START, null);

  // --- post-processing ---
  // The whole grade lives in core/post.js. `ctx.pipeline` stays pointed at the
  // DefaultRenderingPipeline because world/ drives bloom weight through it per
  // zone, and that is a contract.
  const post = new Post(ctx, cam);
  const pipeline = post.init();
  ctx.post = post;
  ctx.pipeline = pipeline;

  // --- loop ---
  const loop = new Loop(ctx);
  ctx.loop = loop;
  loop.bind();
  loop.start();

  engine.runRenderLoop(() => {
    loop.tick();
    scene.render();
  });

  const onResize = () => {
    engine.resize();
    ctx.emit(EV.RESIZE, { width: engine.getRenderWidth(), height: engine.getRenderHeight() });
  };
  window.addEventListener('resize', onResize);
  document.addEventListener('visibilitychange', () => {
    loop.setPaused(document.hidden);
  });

  await scene.whenReadyAsync();

  // --- auto quality benchmark ---
  // Skipped in capture mode: captures must be deterministic and preset-pinned.
  if (!config.captureMode && !opts.preset) {
    setTimeout(() => autoQuality(ctx), 2500);
  }

  // Expose for the capture/perf harness and for console debugging.
  window.SVU = { ctx, engine, scene, loop, config, pipeline, post };
  // Exposed for tools/world-mock.mjs, which patches the live scene to compare
  // art directions. Costs nothing and never runs in a shipped path.
  window.SVU.BJS = BJS;
  window.SVU.ready = true;
  return ctx;
}

/**
 * Step the quality preset down if the first couple of seconds are slow.
 * Deliberately one-directional: dropping quality on a struggling device is a
 * clear win, while stepping up risks oscillating between presets.
 */
function autoQuality(ctx) {
  const p95 = ctx.loop.p95FrameMs();
  if (p95 < 20) return; // comfortably above 50fps, leave it alone

  const order = ['high', 'medium', 'low'];
  const i = order.indexOf(ctx.config.presetName);
  if (i < 0 || i >= order.length - 1) return;

  const next = order[i + 1];
  ctx.config.setPreset(next);
  const q = QUALITY[next];
  ctx.engine.setHardwareScalingLevel(1 / q.scale);
  if (ctx.post) ctx.post.setPreset(next);
  if (ctx.pipeline) ctx.pipeline.bloomWeight = q.bloomScale;
  ctx.emit(EV.QUALITY_CHANGE, { preset: next });
  // Re-check once more after the change settles.
  ctx.loop.frameCount = 0;
  setTimeout(() => autoQuality(ctx), 3000);
}

// Auto-boot unless the harness asked to drive it manually.
if (!window.__SVU_MANUAL__) {
  const params = new URLSearchParams(location.search);
  boot({
    debug: params.has('debug'),
    preset: params.get('q') || undefined,
    capture: params.has('capture'),
    seed: params.has('seed') ? parseInt(params.get('seed'), 10) : undefined,
  }).catch((err) => {
    console.error('[svu] boot failed', err);
    const el = document.getElementById('boot');
    if (el) el.textContent = 'Failed to start: ' + (err && (err.message || err.toString()) || 'unknown');
  });
}

window.SVUBoot = boot;
